dxw/dalmatian-tools

- bin/configure-commands/update
* This was only needed because this repo was private, but it's now public 🎉
> Remove requirement for GitHub token in update command

- bin/configure-commands/update
- bin/dalmatian
* If an update fails for whatever reason, it can cause issues using dalmatian-tools. This adds an update check, to ensure an update has comepleted successfully before attempting to run any commands.
* An `update-check.json` file is stored in the `.config/dalmatian` directory, which contains a `complete_status`. When an update is started, this is set to 0, and then set to 1 when it completes.
> Add update check

- bin/config/list-environments
- bin/config/list-infrastructures
- bin/config/list-services
- bin/config/list-services-by-buildspec
Update the config scripts to use DALMATIAN_CONFIG_PATH if set so that people
who override the default get the correct results.
> Use DALMATIAN_CONFIG_PATH if set

- bin/configure-commands/update
* Fixed the `UPDATE_CHECK_JSON` jq so that it actually sets the `complete_status` to 0 at the beginning of the update
> Fix update check initial value

- bin/configure-commands/update
- bin/setup
* Sometimes terraform will be linked rather than tfenv in homebrew, which causes the `.terraform-version` files to not be respected.
* This forces a brew link for tfenv
> Ensure tfenv is used

- bin/aws-sso/login
* To get the expiration of an SSO token, a grep is used to search the json files in `~/.aws/sso/cache`. However the grep can return multiple results if aws-sso has been logged in with simliar urls, which causes the `registrationExpiresAt` unreadable.
* This adds escaped quotes to the grep to ensure only an exact match will be returned
> Fix SSO Start URL cache search

- bin/configure-commands/update
* We conly care about tracked files that are changed. This adds the `-uno` flag in the `git status` command to not list untracked files
> Fix local changes check

- bin/terraform-dependencies/get-tfvars
* If the tfvars line within the global tfvars contains `[`,`]` or `*`, it will break the grep.
* This adds in a sed to escape those characters
> Fix new tfvars grep

- bin/aws-sso/generate-config
- lib/bash-functions/append_sso_config_file_assume_role.sh
* The region is required in the aws configuration
> Fix: Add region to external account config

- bin/terraform-dependencies/run-terraform-command
* When running Terraform commands with `-var-file`, they need to be placed before any other coammand parameters.
* This places the `-var-file` parameters directly after the intial command, when needed (eg. for plan/apply/console/import)
> Fix run-terraform-command `-var-file` parameter placement

- bin/terraform-dependencies/run-terraform-command
* If the command is a single word, the cut for POST_OPTIONS to get all fields from the second field, will just return the first word.
* This adds a condition to only parse the POST_OPTIONS if there is more than 1 word.
> Fix run-terraform-command post options

- bin/deploy/infrastructure
* If the workspace name is provided, do not select the workspace based on the individual environment/infrastructure/account parameters
> Fix infrastructure deploy workspace selection

- bin/terraform-dependencies/create-import-file
- bin/terraform-dependencies/link-import-file
- lib/bash-functions/append_import_block.sh
* This adds 2 commands for `terraform-dependencies - `create-import-file` and `link-import-file`
* `create-import-file` is a helper tool, which can be used to easily create import blocks. Given a resource reference, it will output the Terraform Documentation URL, to the import section, showing wether the 'id' needs to be the 'id', 'arn' or name. Once both `to` and `id` are provided, it will output the import block to the given location.
* `link-import-file` creates a symlink to either the temporary Account Bootstrap or Infrastructure module, allowing the import blocks to be read whilst running dalmatian terraform commands (eg. a deploy)
> Add terraform import commands

- bin/dalmatian
* "$EDITOR" is used to open and edit files, so that a prefered editor can be used
* If it's not set, the scripts fail. This change sets the EDITOR env to "nano" (probably most user friendly) if it is not already set
> Set EDITOR env

- bin/deploy/account-bootstrap
- bin/terraform-dependencies/get-tfvars
* The account bootstrap is ran on the main dalmatian account, to upload tfvars files.
* If a new account is bootstrapped, the file is stored locally, and specified in the `~/.config/dalmatian/.cache/tfvars-paths.json` file, which is passed through to terraform when an apply is made.
* If another user then runs the account bootstrap on the main dalmatian account, without first running `dalmatian terraform-dependencies get-tvars`, this causes the new tfvars file to be removed from the tfvars S3 bucket.
* This change allows `get-tfvars` to be ran, to download only new tfvars files (ones that don't exist on the local machine) and added to the `tfvars-paths.json` files (by using the `-n` flag). `get-tfvars -n` is then ran everytime the account bootstrap is ran against the main dalmatian …
> Pull new tfvars on main Dalmatian account bootstrap

- bin/aws-sso/login
* If the session in the browser has expired, it can cause the `ExpiresAt` parameter to be incorrect.
* This checks that the `ExpiresAt` field is in the future, and if not will prompt the user to log out of AWS in the browser
> Check AWS SSO login succeeds

- bin/configure-commands/update
* When developing on dalmatian-tools, it checks for any local changes before updating, and prompts the developer to chose if they want to skip the update. However, if the changes are commited, it doesn't detect them.
* This adds in a check, to see if the current tag (which will be eg. v0.22.3-abcdef) trimmed (everything before the `-`), is the same as the latest remote tag. When this happens, it means it is currently on a different branch without any uncommited changes.
> Prevent update if changes are committed on new branch

- bin/terraform-dependencies/v2/get-tfvars
* When running `terraform-dependencies get-tfvars -n`, to download newer tfvars, it will download tfvars that exist in the remote s3 bucket, but not locally
* This change ensures that it also downloads tfvars from the remote, if the modified date is later than the local file. This ensures that all fires are up to date before running the account bootstrap on the main dalmatian account, which uploads them.
> Download later modified tfvars

- bin/terraform-dependencies/v2/get-tfvars
* Pipeing into `gdate` causes unexpected results. This now gets the date into a var, then uses the `gdate` command as normal to get the date in seconds.
* Fixes a variable typo
* Adds the logic to the infrastructure tfvars, as this was missed
> Fix terraform-dependencies get-tfvars

- bin/configure-commands/v2/update
* Now that the `terraform-dependencies get-tfvars` command correctly updates the tfvars, without overwriting local changes, it will be prefereable to use this option during an update to prevent destroying any local changes someone has made - As an update will run automatically on any command if an update is available.
> Only get new tfvars on update

- bin/configure-commands/v1/login
* The path for mfa and awscli-version require the `v1` directory
> Fix v1 login script

- bin/service/v2/container-access
- terraform-project-versions.json
* Bumps the terraform-dxw-dalmatian-infrastructure project to v0.22.2, which contains a fix to allows executing commands on ECS containers
* Adds the service container-access command for V2. This has the added capabilities of being able to change the command ran, and wether it's interactive or not.
> Add V2 service container-access command

- bin/aurora/v1/import-dump
* The ecs file-upload script now resides in a `v1` directory
> Fix aurora import-dump, ecs file-upload script location

- .gitignore
* Its useful sometimes to be able to create custom or personal scripts, that use the dalmatian-tools envars and functions (Rather than trying to only deal with the output from built-in commands).
* Having this directory here, gitignored, allows scripts to be added and then ran with: ``` dalmatian custom my-script ```
> Add custom script directory

- bin/cloudtrail/v2/query
- lib/bash-functions/resolve_aws_profile.sh
* Adds a command which allows querying the CloudTrail logs via Athena, given a Dalmatian account name and SQL query
* The dalmatian account bootstrap creates the Trail and Athena database/table to query the S3 bucket storing the logs. The naming of the Athena resources are consitent, which allows this command to target the correct Athena workgroup
* To allow for easier querying, the keyword 'CLOUDTRAIL' is to be used within the given query, which will be replaced with the actual table name, eg:
```
dalmatian cloudtrail query \
-a 123456789112-eu-west-2-my-account \
-Q "select * from CLOUDTRAIL limit 10;"
```
* Currently the output is the full JSON Athena reult. We can expand on
this to provide common useful CloudTrail queries
> Add `cloudtrail query` command

- renovate.json
* Configures 2 custom managers, 1 for each terraform project (terraform-dxw-dalmatian-infrastructure and terraform-dxw-dalmatian-account-bootstrap), to update the version number within terraform-project-versions.json
> Configure Renovate to auto update the terraform-project-versions

- renovate.json
* `Custom Manager contains disallowed fields: datasource, depName, versioning`
* Needs to use *Template instead
* Adds `customType` of `regex`
> Fix renovate terraform project versions

- data/tfvars-templates/infrastructure.tfvars
* Adds default `infrastructure_ecs_cluster_logspout_command` tfvar
> Add terraform-dxw-dalmatian-infrastructure v0.29.0 tfvars

- lib/bash-functions/resolve_aws_profile.sh
* This can happen if a new infrastructure has been craeted on one machine, and then the second manchine attempts to run a command on that infrastructure, without first having updated the aws profile configuration.
* This catches the issue, displays a useful message (to run `dalmatian aws-sso generate-config`), and exits
* There doesn't seem to be a good place to run this automatically, without having it run when it doesn't need to (Which will make the commands run slower)
> Exit `resolve_profile` if the profile doesn't exist

- lib/bash-functions/aws_epoch.sh
* AWS would recommend we use this instead of hardcoding a single timeserver https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-time-sync-internet-public-ntp-service/
> Use recommended domain name for NTP

- lib/bash-functions/err.sh
- lib/bash-functions/log_info.sh
- lib/bash-functions/read_prompt_with_setup_default.sh
For the sake of readability I made the `[!] Error:` and `==>` bits of the log outputs coloured.
Also fixed a warning output for one of the bash functions
> Use pretty colours for echo functions

- bin/aws-sso/v2/login
* If a user's SSO session is still valid and they run 'aws-sso login' again, there would be no output. This change ensures there is at least a final confirmation message
> Move success message to end of script

- bin/aws-sso/v2/login
* The aws-sso login is ran in the main dalmatian script. If it's the parent script, it runs without `QUIET_MODE`. To make the message make more sense, have it always display the attemping login message. Without this move, it can just output: "You're already logged in"
> Move aws-sso login message

- bin/aws-sso/v2/run-command
* The `resolve_profile` accepts the account name, not infrastructure workspace name. Also the script wasn't even passing it through the the `resolve_profile` function
> Fix aws-sso run-command on account

- bin/dalmatian
* Ensures that if `-q` is passed to a command, that the top level (parent script) login respects `QUIET_MODE`
> Fix login quiet mode

- bin/terraform-dependencies/v2/clean-tfvars-cache
- bin/terraform-dependencies/v2/get-tfvars
* This command checks for any tfvar files in the cache (`~/.config/dalmatian/.cache/tfvars`) that are no longer required - eg. when an infrastructure or account is deleted, and the workspace no longer exists
* The command has been added to the end of `get-tfvars`, so that it will run automatically periodically (eg. during an update). This will keep the cache free of any old/unwanted tfvar files.
> Add `terraform-dependencies clean-tfvars-cache` command

- data/tfvars-templates/infrastructure.tfvars
- terraform-project-versions.json
* https://github.com/dxw/terraform-dxw-dalmatian-infrastructure/compare/v0.31.3...v0.32.0
> Bump terraform-dxw-dalmatian-infrastructure v0.32.0

- bin/s3/v2/empty-and-delete-bucket
* Recursively removes objects
* Deletes all Versions and Dele Markers (required for versioned buckets)
* Deletes the S3 bucket
> Add `s3 empty-and-delete-bucket` command

- bin/s3/v2/list-bucket-properties
* Lists the properties of all buckets within an environment
* Currently checks that no ACLs have been added, blocks public access and that the bucket owner has full control
* A single bucket name can be provided rather than listing them all
> Add `s3 list-bucket-properties` command

- bin/dalmatian
- bin/terraform-dependencies/v2/view-tfvars
This allows users to view tfvars files without triggering the deploy process if they were using set-tfvars instead.
> Add a script to view tfvars files

- bin/rds/v2/run-command
- lib/bash-functions/resource_prefix_hash.sh
* This command will launch a Fargate container, using the 'rds-tooling' image and task definition created by Dalmatian.
* The provided command will be used to overwrite the command in the original task definition.
* The command must be compatible with mysql or psql (eg. not a shell command). The engine will be selected based on the chosen RDS.
* Once the container has launched, the script will begin to tail logs for the running task, and will stop tailing when the container has stopped.
* Adds a `resource_prefix_hash` function, which returns the same resource prefix hash as is created in Terraform
> Add V2 rds run-command

- bin/rds/v2/shell
* This command will launch a Fargate container, using the 'rds-tooling' image and task definition created by Dalmatian.
* It runs the `keep-alive` script, which allows the container to run for a specified amount of time, or stopped when the running shell is exitted. `aws ecs execute-command` is then ran to gain direct shell to the RDS (mysql or psql)
* Depends on the PR https://github.com/dxw/dalmatian-sql-backup/pull/17
> Add V2 rds shell command

- bin/ecs/v1/remove-from-transfer-bucket
- bin/ecs/v1/upload-to-transfer-bucket
This is so we can get files from a localhost to the ECS cluster or elsewhere
and then tidy up afterwards
> Add commands to upload and remove files from transfer bucket

- bin/aws/v2/exec
This is basically an easier way to run `dalmatian aws-sso run-command` and
matches what we had in v1.
Also introduces DALMATIAN_TOOLS_DEBUG to enable debugging output for a script
using `set-x` if it is set.
> Add the v2 version of the aws exec command

- data/tfvars-templates/infrastructure.tfvars
* The tfvars template headers can't contain `/` - It causes a failure when modifying a new infrastructure tfvars from within 'get-tfvars'
> Fix infrastructure tfvars template

- bin/waf/v1/cf-ip-block
```shell
% dalmatian waf cf-ip-block -w wordpress-1 -i dxw-govpress -e staging -6
==> Assuming role to provide access to dxw-govpress infrastructure account ...
==> Listing IP Set dxw-govpress-wordpress-1-waf-staging-blocked-ipv6...
[]
% dalmatian waf cf-ip-block -w wordpress-1 -i dxw-govpress -e staging -b '100::/32' -6
==> Assuming role to provide access to dxw-govpress infrastructure account ...
==> Updating IP Set dxw-govpress-wordpress-1-waf-staging-blocked-ipv6...
["0100:0000:0000:0000:0000:0000:0000:0000/32"]
% dalmatian waf cf-ip-block -w wordpress-1 -i dxw-govpress -e staging -b '0100:0000:0000:0000:0000:0000:0000:0000/32' -d
==> Assuming role to provide access to dxw-govpress infrastructure account ...
==> Updating IP Set dxw-govpress-wordpress-1-waf-staging-blocked-ipv6...
[] …
```
> Command to modify Cloudfront IP sets

- bin/rds/v2/run-command
- bin/rds/v2/shell
- bin/utilities/v2/run-command
- terraform-project-versions.json
* The RDS Tooling container has been changed to a more generic Utilities container (Along with the task definition)
* This changes the command to select the correct task definition (If an RDS name is supplied), and moves it to the more generic `utilities run-command` command. The `rds shell` and `rds run-command` scripts have been updated to use this new command
> Change `rds tooling-container-run-command` to `utilities run-command`

- bin/utilities/v2/run-command
- lib/bash-functions/resource_prefix_hash.sh
Not all things we use the infrastructure environment hash for need
to have a letter prepended if the hash starts with a number.
This special cases this with an option and then uses it for rds names.
> Special case the addition of a letter to the hash
