dxw/dalmatian-tools

data/tfvars-templates/infrastructure.tfvars
terraform-project-versions.json

* https://github.com/dxw/terraform-dxw-dalmatian-infrastructure/compare/v0.22.0...v0.22.1
* Adds new infrastructure tfvars

Bump terraform-dxw-dalmatian-infrastructure v0.22.1

---

bin/configure-commands/v2/update

* Needs a `||` rather than `&&` in the condition

Fix dalmatian update

---

data/tfvars-templates/infrastructure.tfvars
terraform-project-versions.json

* https://github.com/dxw/terraform-dxw-dalmatian-infrastructure/compare/v0.22.2...v0.23.0

Bump terraform-dxw-dalmatian-infrastructure v0.23.0

---

terraform-project-versions.json

* https://github.com/dxw/terraform-dxw-dalmatian-account-bootstrap/compare/v0.9.9...v0.9.10

Bump terraform-dxw-dalmatian-account-bootstrap v0.9.10

---

data/tfvars-templates/infrastructure.tfvars
terraform-project-versions.json

* terraform-dxw-dalmatian-infrastructure v0.24.0: https://github.com/dxw/terraform-dxw-dalmatian-infrastructure/compare/v0.23.0...v0.24.0
* terraform-dxw-dalmatian-account-bootstrap v0.9.11: https://github.com/dxw/terraform-dxw-dalmatian-account-bootstrap/releases/tag/v0.9.11

Bump terraform projects v0.24.0 and v0.9.11

---

data/tfvars-templates/infrastructure.tfvars
terraform-project-versions.json

* https://github.com/dxw/terraform-dxw-dalmatian-account-bootstrap/compare/v0.9.11...v0.9.12
* https://github.com/dxw/terraform-dxw-dalmatian-infrastructure/compare/v0.24.0...v0.25.0

Bump terraform projects v0.9.12 and v0.25.0

---

bin/deploy/v2/infrastructure

* Allows the plan output and show parameters to work if the workspace name has been provided

Fix plan output and show

---

terraform-project-versions.json

* https://github.com/dxw/terraform-dxw-dalmatian-account-bootstrap/compare/v0.9.12...v0.9.13
* https://github.com/dxw/terraform-dxw-dalmatian-infrastructure/compare/v0.25.0...v0.25.1

Bump Terraform projects

---

terraform-project-versions.json

* https://github.com/dxw/terraform-dxw-dalmatian-infrastructure/compare/v0.25.1...v0.25.2

Bump terraform-dxw-dalmatian-infrastructure v0.25.2

---

terraform-project-versions.json

* https://github.com/dxw/terraform-dxw-dalmatian-infrastructure/compare/v0.25.2...v0.26.0

Bump terraform-dxw-dalmatian-infrastructure v0.26.0

---

bin/util/v1/generate-four-words

FIX relative path to dictionary

---

bin/aws-sso/v2/login
bin/dalmatian

* The main dalmatian script is called by other scripts, expecting a consitent output

Set parent dalmatian script's sso login to quiet

---

lib/bash-functions/warning.sh

* Allows displaying a warning, colored yellow, which is output to stderr

Add `warning` bash function

---

data/tfvars-templates/infrastructure.tfvars

Add default datadog-app-key

---

data/tfvars-templates/account-bootstrap.tfvars
terraform-project-versions.json

* https://github.com/dxw/terraform-dxw-dalmatian-account-bootstrap/compare/v0.11.4...v0.12.0

Bump terraform-dxw-dalmatian-account-bootstrap v0.12.0

---

terraform-project-versions.json

* https://github.com/dxw/terraform-dxw-dalmatian-infrastructure/compare/v0.32.1...v0.33.0

Bump terraform-dxw-dalmatian-infrastructure v0.33.0

---

terraform-project-versions.json

* https://github.com/dxw/terraform-dxw-dalmatian-infrastructure/compare/v0.33.1...v0.34.0

Update dependency dxw/terraform-dxw-dalmatian-infrastructure to v0.34.0

---

bin/configure-commands/v2/update

This is not needed anymore as it we are now installing Session Manager into user dir

Remove sudoer gate

---

bin/configure-commands/v2/update

Fix minor typo

---

terraform-project-versions.json

* https://github.com/dxw/terraform-dxw-dalmatian-infrastructure/compare/v0.34.1...v0.34.2

Bump bump-terraform-dxw-dalmatian-infrastructure v0.34.2

---

bin/service/v2/set-environment-variables

fix typo: exitting

---

data/tfvars-templates/infrastructure.tfvars

* Defaults to not adding any tags or delay

Add custom resource tag defaults

---

terraform-project-versions.json

* https://github.com/dxw/terraform-dxw-dalmatian-infrastructure/compare/v0.35.1...v0.36.0

Bump terraform-dxw-dalmatian-infrastructure v0.36.0

---

terraform-project-versions.json

- Adds support for using RDS managed root passwords

Bump infrastructure module to v0.37.0

---

renovate.json

* https://docs.renovatebot.com/upgrade-best-practices/
* Extending `config:best-practices` includes security best practices (eg. pinning versions using digests)

 Update renovate to extend `config:best-practices`

---

terraform-project-versions.json

* https://github.com/dxw/terraform-dxw-dalmatian-account-bootstrap/compare/v0.12.2...v0.13.1
* https://github.com/dxw/terraform-dxw-dalmatian-infrastructure/compare/v0.40.0...v0.40.1

Bump terraform projects v0.13.1 and v0.40.1

---

terraform-project-versions.json

* https://github.com/dxw/terraform-dxw-dalmatian-account-bootstrap/compare/v0.13.1...v0.13.2
* https://github.com/dxw/terraform-dxw-dalmatian-infrastructure/compare/v0.40.1...v0.40.2

Bump terraform project v0.13.2 and v0.40.2

---

terraform-project-versions.json

* https://github.com/dxw/terraform-dxw-dalmatian-account-bootstrap/compare/v0.13.2...v0.13.3

Bump terraform-dxw-dalmatian-account-bootstrap v0.13.3

---

terraform-project-versions.json

* https://github.com/dxw/terraform-dxw-dalmatian-infrastructure/compare/v0.41.1...v0.43.0

Bump terraform-dxw-dalmatian-infrastructure v0.43.0

---

bin/cloudfront/v1/logs
bin/cloudfront/v2/logs

and modernise the v1 command to use the new log format function.

Add a v2 command to download CloudFront logs

---

data/tfvars-templates/infrastructure.tfvars

* Defaults to not deploy any custom lambdas

Fix: Add custom lambdas default variable
